### ISSUE TITLE
ERR: Can't find variable: ResizeObserver in Safari

### ISSUE THREAD

**Issue by dellwatson** [dbismut/react-soft-slider#13]
i wanted to use this module, but it seems safari has problem,

every examples if open in safari also couldnt work.

**Comment by dbismut** [comment]
Hm this is typically a polyfill issue. Does this example throw an error? https://codesandbox.io/s/nwj6597vq4?codemirror=1

**Comment by dellwatson** [comment]
oh yeah that works too,

anyway there's another way, the use-resize-observer module has been updated.
just add extension of the module 'use-resize-observer/polyfilled'
in src/index.tsx.

Imnot sure if there's any significance difference, i didnt use much resizeObserver,
but pretty much clean everything, i don't need to add module 'resize-observer-polyfill' and
SSR dont need to tweak the "window" problem

anyway your works is amazing 🙌🏻

**Comment by dbismut** [comment]
Hey @dellwatson sorry I’ve rejected your PR prior to reading your comment but as explained I think the user should be responsible for polyfilling the way he/she wants, for the whole project. 

The way use-resize-observer exposes its polyfill is by injecting resize-observer-polyfill, so one way or another you’ll be using it :)
