### ISSUE TITLE
With SSR: IntersectionObserver is not defined

### ISSUE THREAD

**Issue by vabatta** [dbismut/react-soft-slider#6]
If you use the carousel with SSR, you get this:
```
ReferenceError: IntersectionObserver is not defined
    at Slider (/home/vbatt/Projects/ia-marketing-web-client/node_modules/react-soft-slider/web.cjs.js:84:49)
```

**Comment by vabatta** [comment]
Also not working on Android phones (firefox). I will take a look at the code.

**Comment by dbismut** [comment]
Ciao @vabatta I've just published 2.0.1 which should fix the SSR issue. As for the Firefox Android I can't test so please let me know what you find out!

**Comment by vabatta** [comment]
Cool, will try asap and give feedback. A bit off topic, but could be useful to convert this to typescript to spot errors (I was looking through the code and I saw some weird / wrong calls, such as `useSprings` using three parameters while it accepts only two).

**Comment by dbismut** [comment]
Yeah you’re right. I’ll move the lib to tsdx when I have some time, maybe this week-end. I’ve been a bit juggling with latest canary and beta versions of react-spring which have some API changes but are inconsistent performance wise at this point.

**Comment by vabatta** [comment]
Cool. Yeah, wrapping into the `useEffect` did the job. I still need to play with this around for a bit to understand more in depth how things are achieved and how to tweak to my specific use case. Even better if this will then be in ts :)

**Comment by dbismut** [comment]
Yeah this was a test project I’m know trying to use it for real and there’s some stuff I’ll input in the next version. The code is a bit complex calculate which slides are visible in order to set the trailing delay.

**Comment by dbismut** [comment]
2.1.0 is now out, written in typescript, using `tsdx`!
