### ISSUE TITLE
Allow classNames to style all elements

### ISSUE THREAD

**Issue by vabatta** [dbismut/react-soft-slider#9]
Would be great to have an option to style the slides, wrapper and container using classNames rather than `inline` styles. The reason is that `inline` styles are hard to override, while allowing custom class names can have the benefit of media queries as well. I don't know the implications on the position computation when it comes to styles that add sizes / margin to the slides tho.

**Comment by dbismut** [comment]
Out in 2.2.0 (`slideClassName`).
